### ISSUE TITLE
Repo adamlauretig/Statisticsandinternationalsecurity fails to access

### ISSUE THREAD

**Issue by JiaxiangBU** [adamlauretig/adamlauretig.github.io#1]
Hi, Adam,

I read your publication related to Manski(1990).

> Lauretig, Adam M, and Bear F Braumoeller. 2018. “Statistics and International Security.” The Oxford Handbook of International Security, 133.

I find you make the code public on GitHub, but I don't find it, would you like to give me the correct repo address (if still public).

> (6.) All code is available for replication at https://github.com/adamlauretig/Statisticsandinternationalsecurity.

Maybe this issue should not be opened here if I could find the access email to contact you.

**Comment by adamlauretig** [comment]
Here you go: https://github.com/adamlauretig/Statistics_and_International_Security.

**Comment by JiaxiangBU** [comment]
@adamlauretig Thanks for your help.
